set_timezone:
  name: Set Time Zone
  description: Configure time zone and daylight savings time on the WS1500 device
  fields:
    host:
      name: Host
      description: IP address of the WS1500 device
      required: true
      example: "192.168.1.198"
      selector:
        text:
    timezone:
      name: Time Zone
      description: Time zone offset from UTC (-12.0 to 12.0)
      required: true
      example: -6.0
      selector:
        number:
          min: -12.0
          max: 12.0
          step: 0.5
          mode: box
    dst:
      name: Daylight Savings Time
      description: Enable or disable daylight savings time
      required: true
      example: "off"
      selector:
        select:
          options:
            - label: "Off"
              value: "off"
            - label: "On"
              value: "on"
